name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.1

      - name: Setup mise
        uses: jdx/mise-action@v3.5.1

      - name: Cache npm dependencies
        uses: actions/cache@v5.0.1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        # This (`npm install) is a workaround for the fact that release-please
        # is not properly updating the lockfile for interdependencies. `npm ci`
        # will fail if more than one package has a version change. This is a bug
        # in release-please, which should be updating the version numbers in release PR.
        run: npm install

      - name: Run Prettier
        run: npm run prettier-check

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        # Have to use extra -- -- because of turbo wrapping
        run: npm run test -- -- --coverage

      - name: Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy-user:dummy-password@dummy-host:5432/dummy-database"
          API_KEY_SECRET: "dummy-api-key-secret"
          PROVIDER_KEY_SECRET: "dummy-provider-key-secret"
          NEXTAUTH_SECRET: "dummy-nextauth-secret"
          NEXTAUTH_URL: "http://localhost:3000"
          SKIP_ENV_VALIDATION: "true"
